apiVersion: v1
kind: Service
metadata:
  name: qr-cluster-service
  labels:
    app: qrjava
    type: qrcode-generator
spec:
  type: ClusterIP
  selector:
    app: qrjava
    type: qrcode-generator
  ports:
  - port: 8080
    targetPort: 8080
  
  

