apiVersion: v1
kind: Service
metadata:
  name: ten-cluster-service
  namespace: default
  labels:
    app: tenants
    type: tenants-service
spec:
  type: ClusterIP
  clusterIP: 10.92.12.1
  selector:
    app: tenants
    type: tenants-service
  ports:
  - port: 80
    targetPort: 8888