apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: default
  labels:
    app: frontend
    type: front-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      type: front-service
  template:
    metadata:
      labels:
        app: frontend
        type: front-service
    spec:
      serviceAccountName: default
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: frontend
        image: eu.gcr.io/qrcode-374515/frontend
        imagePullPolicy :  Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
