apiVersion: v1
kind: Service
metadata:
  name: qr-nodeport
  labels:
    app: qrjava
    type: qrcode-generator
spec:
  type: NodePort
  selector:
    app: qrjava
    type: qrcode-generator
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  
