apiVersion: apps/v1
kind: Deployment
metadata:
  name: his-deployment
  namespace: default
  labels:
    app: qrhistory
    type: qrcode-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrhistory
      type: qrcode-history
  template:
    metadata:
      labels:
        app: qrhistory
        type: qrcode-history
    spec:
      serviceAccountName: default
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: qrhistory
        image: eu.gcr.io/qrcode-374515/history-service
        ports:
        - containerPort : 8888
        imagePullPolicy :  Always
        env:
        - name: BUCKET_NAME
          value: "default-logo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
